### ISSUE TITLE
Epic #25 - Applications process remaining

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#303]
### Backlog:
- [ ] #169 Simplify mutation after strict validation of ApplicationPage to run a single instead of many - Effort 1
- [ ] #185 Add timeout to Polling queries (e.g. useTriggerProcessing) - **Effort to-be-decided**
- [ ] #187 Cache security - **Effort to-be-decided**
- [ ] #188 Cache management after offline - **Effort to-be-decided**
- [ ] #102 Optimistic UI for responses - **Effort to-be-decided** 
- [ ] #60 ApolloError handling for server not reachable on ApplicationPage - Effort 1
- [ ] #106 Save application when user leaves the application page (example: Go back to see application list) - **Effort to-be-decided** 
- [ ] #186 When loading new application, cursor/keyboard focus should go to input of first form element. - **Effort to-be-decided**
