### ISSUE TITLE
UI to show applicant which questions need updating (Application Page & Application Summary)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#441]
`Andrei comments`
I've been working on duplicating application responses and progress of changes : https://github.com/openmsupply/application-manager-server/pull/254 and https://github.com/openmsupply/application-manager-web-app/pull/445

This one would need both. 

I think it should be broken down as follows:

- [x] part 1, slight changes to ProgressBarNew, with test branch demonstrating how application response are duplicated and what can be used to display changes requested
- [x] part 2 - making Application Page UI as designs
- [x] part 3 - making ApplicationSummary UI as designs  ~ **In PR**

`end of Andrei comments`

Changes to the Application Page to display icons for "Changes requested" questions (from LOQ) and "Changed" questions by Applicant choice.

To be done (in parallel) or after #437.

**To be decided:**
* Should also cover applicant making changes to each question ?
* What to do about bottom progress, what progress is it showing ?

As new designs show:
* Progress bar to show "Invalid" in pages where there are Changes requested in LOQ
* ![Screen Shot 2021-03-15 at 2 50 17 PM](https://user-images.githubusercontent.com/16461988/111093450-d1bb3a00-859d-11eb-9685-bedd6a551106.png) icon showing below the "Changes required" before a new response is added.
* ![Screen Shot 2021-03-15 at 2 50 27 PM](https://user-images.githubusercontent.com/16461988/111093474-e7c8fa80-859d-11eb-87cd-20740df4acdd.png) icon showing below the "Changes required" after a new response is added.
* ![Screen Shot 2021-03-15 at 2 50 36 PM](https://user-images.githubusercontent.com/16461988/111093498-f8797080-859d-11eb-9bcc-acf034e35c10.png) icon showing below a response without changes required after a new response is added.
* ![Screen Shot 2021-03-15 at 2 55 02 PM](https://user-images.githubusercontent.com/16461988/111093696-7178c800-859e-11eb-9016-7646d0b96cf4.png) label + icon + date besides new responses added (in the Summary page).

### Designs
![Screen Shot 2021-03-15 at 2 47 44 PM](https://user-images.githubusercontent.com/16461988/111093597-3b3b4880-859e-11eb-819d-1d5291b9da79.png)
![Screen Shot 2021-03-15 at 2 47 10 PM](https://user-images.githubusercontent.com/16461988/111093598-3c6c7580-859e-11eb-86ae-cac5488155ee.png)
![Screen Shot 2021-03-15 at 2 47 57 PM](https://user-images.githubusercontent.com/16461988/111093593-38405800-859e-11eb-86c3-5258a965e997.png)

**Comment by nmadruga** [comment]
Few things come up in the meeting today:
* On the ApplicationSummary should leave open what was changed on the latest submission
* Make Also summary display what changes were request and not request but changed too (as Part 3)
* Should have a toggle to show all or just questions submitted in last submission?
* Should we change the Submission message when user re-submits?

**Comment by nmadruga** [comment]
Ok, this one isn't finished yet too. Still has one issue to do (I will be working on it this week so moving to `Sprint27`)
