### ISSUE TITLE
Epic #47 - Display available actions

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#506]
## Description

Each user should see their possible actions to act on each application - based on their role (permissions). The options are visible on the applications list and on each application/review home page. 

Users might have more than one role sometime (e.g. Reviewer, Assigner). And that should result usually in more than one action available.

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 25:
- [ ] #227 Display actionable in cell on column for Reviewer and Consolidator - Effort 3 ~**In Progress**
- [ ] #189 Display 'changes requested' on application list next to applications - Effort 2 ~**In Progress**

### Sprint 26:
- [ ] #293 Show Action to Assign/Re-assign in applications for Assigner user in the List view (would be good if could be using the current user permission) - Effort 3
- [ ] #310 Document and create new filter to list application assigned/not assigned - **Effort to be decided**
- [ ] #311 Deal with users that have more than on roles: Assigner and others - **Effort to be decided**
- [ ] #474 Documentation on actions displaying on each application for different users - Effort 1
