### ISSUE TITLE
Update layout and use global styles: All remaining elements

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#662]
Add things here for elements that still need styling, so we can "mop up" in one issue:

- [ ] Review decision area styles (part 1 in PR #682)
- [x] `isChangeRequest` in PageElements (in PR --  #684)
- [ ] Error message pointer should be label with icon as per design
- [x] "Help" sidebar implementation & style (in PR -- #683)
- [ ] Application Summary page:
   - [ ] Change requests (should match layout and styles of Review page)
   - [ ] Summary Review Response Element (should be very similar (if not a variant of) ReviewDecisionElement
- [ ] Check application/reviews in all states (i.e. changes requested, etc.)
- [ ] Consolidate/refactor common styles

**Comment by nmadruga** [comment]
@CarlosNZ also can this one be closed? I think that's the only remaining issue for [Epic#10](https://github.com/openmsupply/application-manager-web-app/issues/78)

**Comment by CarlosNZ** [comment]
I dunno, maybe move it to another epic if you want to close #10. I feel like there's some things we need to have a more thorough look at (the unchecked items) but they're not an immediate priority.

**Comment by nmadruga** [comment]
Yes, good idea to create separated issues for those and link to Epic #25 - Others. So we can close this issue. I have already moved Epic #10 to Column "Epics Done" so we can have a better feel of what is currently in progress really
