### ISSUE TITLE
Epic #7 - Actions & Questions plugins

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#74]
## Description
Each new Question and Action plugin should be added in their own bundles to a specific folder in the Backend (?) repo.
The plugins are automatically imported to the App when the system runs using dynamic importing.
Creation of basic actions and plugins - to be used in "User Registration", "Create company" and "Join company" applications.
Documented mechanism of import and usage of Actions plugins and Question plugins.

### Sprint 1:
- [x] #21 Docs -- add Action plugin specification - Effort 2
### Sprint 4:
- [x] [Back-end#27](https://github.com/openmsupply/application-manager-server/issues/27) Diagram for question structure meeting
- [x] [Back-end#28](https://github.com/openmsupply/application-manager-server/issues/28) Question structure meeting
- [x] #15 Core Question Plugs-in skeleton
- [x] #55 New Action to create users - Effort 4

### Backlog:
- [ ] (?) Webpack Federation Module and Question Plugs-in
