### ISSUE TITLE
Epic #[number here] Question (Form Element) Plugins

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-web-app#75]
### Description

Plugify form element (question plugin). 

Make it work for development and production: https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes

Core plugins - Incorporated into the app
Remote plugins - Can be 'imported' in productions, have their own repositories

https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes

TODO: Create Issues
TODO: Link to deliverables

### Issues

- [ ] https://github.com/openmsupply/application-manager-web-app/issues/15 Implement core plugin functionality
- [ ] [insert issue] REST endpoint on backend to get plugin manifest
- [ ] [insert issue] Implementation of remote plugins

- [ ] docs internal
- [ ] docs external
- [ ] docs plugin development guid
