### ISSUE TITLE
Dashboard styles to be aligned with latest designs

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#824]
Remove "view alls"
Make the header navigate to the list
Remove icons form config
Pluralisation of strings (by Carl)

**Comment by CarlosNZ** [comment]
> Pluralisation of strings (by Carl)

Just to clarify what this refers to: currently when there is only 1 application, it still shows a plural, e.g. "1 Draft Applications"

Suggestion is to format it like "Draft Applications(1)" or "Draft Applications: 1", so we don't have to worry about pluralisation

**Comment by nmadruga** [comment]
Cool. Thanks for explaining this Carl. I should start on this tomorrow morning - almost time to go now.

**Comment by nmadruga** [comment]
- [x] Overall layout
- [x] Remove "view alls"
- [ ] Make the header navigate to the list WIP
- [ ] Remove icons form config
- [ ] Pluralisation of strings (by Carl)
