### ISSUE TITLE
Epic #11 - JWT Token & Permissions

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#93]
## Description
Current user permission are been kept per user based on:
a) What is selected in each Application (Permission fields); or 
b) What is granted to a user after login (e.g. DFA user are granted with basic review permission).
When the user can login a JWT is generated by Back-end with all the permissions that the user have which is used on the Front-end for listing options and checking page access.

### Sprint 7:
- [ ] #65 Define how front-end request the list of templates and actions for the current user

### Sprint 8:
- [ ] [Back-end#84](https://github.com/openmsupply/application-manager-server/issues/84) Back-end creation of JWT with user permissions + login endpoint

## Add new issues
- [ ] Add restriction on DB based on current user logged in
- [ ] Create action to update user permission after 'Join Company' application is approved
- [ ] Add users with different permissions in script to start the database
- [ ] List applications based on permission of Applicant user
- [ ] List applications based on permission of Reviewer user
- [ ] List applications based on permission of Supervisor/Assigner user

## Design
- Wireframes for Desktop: https://debs181572.invisionapp.com/console/share/6N1N4YOR4Y
- Wireframes for Mobile: https://debs181572.invisionapp.com/console/share/3K1MPN0GGM
